language: php

sudo: false

branches:
  only:
    - 1.0
    - master

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql

before_install:
  - if [[ $DB == 'mysql' && $MYSQL_VERSION == '5.7' ]]; then ./tests/travis/install-mysql-5.7.sh; fi
  - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'select version()'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -U postgres -c 'SHOW SERVER_VERSION'; fi
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

script: ./vendor/bin/phpunit -c tests/travis/$DB.travis.xml

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest" DB=sqlite
    - php: 7.1
      env: NAME="MySQL 5.6" DB=mysql
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - mysql-server-5.6
          - mysql-client-core-5.6
          - mysql-client-5.6
    - php: 7.1
      env: NAME="MySQL 5.7" DB=mysql MYSQL_VERSION=5.7
      sudo: required
    - php: 7.1
      env: NAME="PostgreSQL 9.2" DB=pgsql
      addons:
        postgresql: 9.2
    - php: 7.1
      env: NAME="PostgreSQL 9.3" DB=pgsql
      addons:
        postgresql: 9.3
    - php: 7.1
      env: NAME="PostgreSQL 9.4" DB=pgsql
      addons:
        postgresql: 9.4
  exclude:
    - php: hhvm
      env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
  allow_failures:
    - php: nightly
    - php: hhvm
