simple_things_entity_audit_home:
    path: /{page}
    defaults:
        _controller: SimpleThingsEntityAuditBundle:Audit:index
        page: 1
    requirements:
        page: \d+

simple_things_entity_audit_viewrevision:
    path: /viewrev/{rev}
    defaults:
        _controller: SimpleThingsEntityAuditBundle:Audit:viewRevision
    requirements:
        rev: \d+

simple_things_entity_audit_viewentity_detail:
    path: /viewent/{className}/{id}/{rev}
    defaults:
        _controller: SimpleThingsEntityAuditBundle:Audit:viewDetail
    requirements:
        rev: \d+

simple_things_entity_audit_viewentity:
    path: /viewent/{className}/{id}
    defaults:
        _controller: SimpleThingsEntityAuditBundle:Audit:viewEntity

simple_things_entity_audit_compare:
    path: /compare/{className}/{id}/{oldRev}/{newRev}
    defaults:
        _controller: SimpleThingsEntityAuditBundle:Audit:compare
        oldRev: ~
        newRev: ~
